//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pastelaria_do_Zé.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pastelaria_do_Zé.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você tem certeza que deseja sair?.
        /// </summary>
        internal static string alertExit {
            get {
                return ResourceManager.GetString("alertExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmação.
        /// </summary>
        internal static string alertTitle {
            get {
                return ResourceManager.GetString("alertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cracha {
            get {
                object obj = ResourceManager.GetObject("cracha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cracha1 {
            get {
                object obj = ResourceManager.GetObject("cracha1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_producao_jpg {
            get {
                object obj = ResourceManager.GetObject("icon.producao.jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_icon_jpg {
            get {
                object obj = ResourceManager.GetObject("image.icon.jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lupa {
            get {
                object obj = ResourceManager.GetObject("lupa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Administrador.
        /// </summary>
        internal static string txtAdministrador {
            get {
                return ResourceManager.GetString("txtAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alerta.
        /// </summary>
        internal static string txtAlerta {
            get {
                return ResourceManager.GetString("txtAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Balcão.
        /// </summary>
        internal static string txtBalcao {
            get {
                return ResourceManager.GetString("txtBalcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar.
        /// </summary>
        internal static string txtCadastrar {
            get {
                return ResourceManager.GetString("txtCadastrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Produto.
        /// </summary>
        internal static string txtCadastrarProduto {
            get {
                return ResourceManager.GetString("txtCadastrarProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro Cliente.
        /// </summary>
        internal static string txtCadastroCliente {
            get {
                return ResourceManager.GetString("txtCadastroCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro Funcionários.
        /// </summary>
        internal static string txtCadastroFuncionario {
            get {
                return ResourceManager.GetString("txtCadastroFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Todos os campos devem ser preenchidos!.
        /// </summary>
        internal static string txtCamposPreenchidos {
            get {
                return ResourceManager.GetString("txtCamposPreenchidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clientes.
        /// </summary>
        internal static string txtClientes {
            get {
                return ResourceManager.GetString("txtClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Config.
        /// </summary>
        internal static string txtConfiguracoes {
            get {
                return ResourceManager.GetString("txtConfiguracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmação.
        /// </summary>
        internal static string txtConfirma {
            get {
                return ResourceManager.GetString("txtConfirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contato.
        /// </summary>
        internal static string txtContato {
            get {
                return ResourceManager.GetString("txtContato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Copyright.
        /// </summary>
        internal static string txtCopiright {
            get {
                return ResourceManager.GetString("txtCopiright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        internal static string txtCPF {
            get {
                return ResourceManager.GetString("txtCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Fiado.
        /// </summary>
        internal static string txtDataFiado {
            get {
                return ResourceManager.GetString("txtDataFiado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        internal static string txtDescricao {
            get {
                return ResourceManager.GetString("txtDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entrar.
        /// </summary>
        internal static string txtEntrar {
            get {
                return ResourceManager.GetString("txtEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esqueci minha Senha.
        /// </summary>
        internal static string txtEsqueciSenha {
            get {
                return ResourceManager.GetString("txtEsqueciSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fiado.
        /// </summary>
        internal static string txtFiado {
            get {
                return ResourceManager.GetString("txtFiado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Funcionários.
        /// </summary>
        internal static string txtFuncionarios {
            get {
                return ResourceManager.GetString("txtFuncionarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        internal static string txtID {
            get {
                return ResourceManager.GetString("txtID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma.
        /// </summary>
        internal static string txtIdioma {
            get {
                return ResourceManager.GetString("txtIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Imagem.
        /// </summary>
        internal static string txtImagem {
            get {
                return ResourceManager.GetString("txtImagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Início.
        /// </summary>
        internal static string txtInicio {
            get {
                return ResourceManager.GetString("txtInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matrícula.
        /// </summary>
        internal static string txtMatricula {
            get {
                return ResourceManager.GetString("txtMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Multa por Atraso (R$).
        /// </summary>
        internal static string txtMultas {
            get {
                return ResourceManager.GetString("txtMultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string txtNome {
            get {
                return ResourceManager.GetString("txtNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome + Matrícula.
        /// </summary>
        internal static string txtNome_Matricula {
            get {
                return ResourceManager.GetString("txtNome/Matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome da Companhia.
        /// </summary>
        internal static string txtNomeCompanhia {
            get {
                return ResourceManager.GetString("txtNomeCompanhia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome Completo.
        /// </summary>
        internal static string txtNomeCompleto {
            get {
                return ResourceManager.GetString("txtNomeCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do Produto.
        /// </summary>
        internal static string txtNomeProduto {
            get {
                return ResourceManager.GetString("txtNomeProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nova Senha.
        /// </summary>
        internal static string txtNomeSenha {
            get {
                return ResourceManager.GetString("txtNomeSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Percentual Diário de Juros.
        /// </summary>
        internal static string txtPercentualJuros {
            get {
                return ResourceManager.GetString("txtPercentualJuros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preço.
        /// </summary>
        internal static string txtPreco {
            get {
                return ResourceManager.GetString("txtPreco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produtos.
        /// </summary>
        internal static string txtProdutos {
            get {
                return ResourceManager.GetString("txtProdutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe seu Email.
        /// </summary>
        internal static string txtRecuperaSenha {
            get {
                return ResourceManager.GetString("txtRecuperaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Re-Senha.
        /// </summary>
        internal static string txtReSenha {
            get {
                return ResourceManager.GetString("txtReSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A apicação será reiniciada.
        /// </summary>
        internal static string txtRestart {
            get {
                return ResourceManager.GetString("txtRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sair.
        /// </summary>
        internal static string txtSair {
            get {
                return ResourceManager.GetString("txtSair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string txtSalvar {
            get {
                return ResourceManager.GetString("txtSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        internal static string txtSenha {
            get {
                return ResourceManager.GetString("txtSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sistema de Cobrança em Atraso.
        /// </summary>
        internal static string txtSistemasCobraca {
            get {
                return ResourceManager.GetString("txtSistemasCobraca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sobre.
        /// </summary>
        internal static string txtSobre {
            get {
                return ResourceManager.GetString("txtSobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pastelaria do Zé.
        /// </summary>
        internal static string txtTituloPrincial {
            get {
                return ResourceManager.GetString("txtTituloPrincial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário.
        /// </summary>
        internal static string txtUsuario {
            get {
                return ResourceManager.GetString("txtUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Versão.
        /// </summary>
        internal static string txtVersao {
            get {
                return ResourceManager.GetString("txtVersao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Voltar.
        /// </summary>
        internal static string txtVoltar {
            get {
                return ResourceManager.GetString("txtVoltar", resourceCulture);
            }
        }
    }
}
